theme: jekyll-theme-slate
title: "The Case for a Virtualization-Based Trusted Execution Environment in Mobile Devices"
name: "The Case for a Virtualization-Based Trusted Execution Environment in Mobile Devices"
show_downloads: true
